# Generated by Django 2.2 on 2020-07-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='fullname',
            new_name='firstname',
        ),
    ]
