# Generated by Django 2.2 on 2020-07-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200726_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('staffid', models.CharField(max_length=50)),
            ],
        ),
    ]
