# Generated by Django 2.2 on 2020-07-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200728_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
